### PR TITLE
Normalize README and script for merging.

### PR DESCRIPTION
**Pull request by thiagowfx**
This commit tries to get the best of all worlds:

- fcpg/vim-osc52
- dohsimpson/vim-osc52
- thiagowfx/vim-osc52

...with the goal of reducing forking, so that we can all use the same
repository and contribute to it together.

cc @dohsimpson FYI

### CODE REVIEW

**Comment by thiagowfx** [comment]
Hey @fcpg, there's no rush if you need more time to review this, but could you let me know if you're considering this patch at all? If you don't intend to accept it I'll close it and move on, but it would be really nice if we could reduce unnecessary forking and use the same plug-in.

The major advantage of this is that `C-c` "just works", and plus there's no need to put a giant line in your `vimrc` (`xmap <F7> y:call SendViaOSC52(getreg('"'))<cr>`); rather, a simple `vmap <C-c> y:Oscyank<cr>`. Thanks.

**Comment by fcpg** [comment]
Sorry for the longer reply, I have been delaying this PR since it was a bit more work than the other open issues. I definitely appreciate the efforts to improve things though, so thank you for that!

These commits break the plugin on my side (vim 8.1 on mintty 3.3 with tmux 3.1b), so I need to investigate what's going on before merging it into master.

**Comment by thiagowfx** [comment]
No worries. Most of the changes are from `dohsimpson/vim-osc52`, and they seemed to be compatible, so I'm surprised it broke your setup. I just did a 2-way merge and tried to get the best of both repositories (better documentation, more intuitive shortcut, etc).

If it turns out to be a hassle to figure out why it breaks your setup though, one possibility would be to start from your repository and then add the other bits (in this case I mostly started from his repository).

**Comment by fcpg** [comment]
The problem turned out to be pretty trivial: it was just the reliance on the `$TMUX` environment variable for setting up the tmux-specific escaping in DCS. The variable is not set on the remote side when tmux is running locally, so the OSC sequence is not properly escaped.

Unless there is an easy way to check from the remote side if the terminal is actually TMUX, we'll need to make some educated guesses and probably offer some user setting for that (eg. check `g:osc52_term` and call the right `s:get_OSC52_` variant). The heuristics from the PR uses `s:get_OSC52_DCS` if 'screen' appears in `$TERM`, is it deliberate? My assumption was that most people used tmux these days, so `screen` was really an indicator of tmux rather than something else. Could we keep this assumption? It would also avoid breaking things for existing users who rely on this behavior.

Less importantly, could you keep the coding/comment conventions, unless there is a clear problem with them? Eg. no space between a function name and the opening parenthesis, or simply stating what a function does in the comment without the "This function..." part that was added to some functions eg. `s:get_OSC52_DCS()`.

Also, in `s:rawecho()`, `execute "silent! !echo " . shellescape(a:str)` was replaced by `exec("silent! !echo " . shellescape(a:str))`, why? `exec` is not a function in vimL, so this does just run the `execute` command with an extra set of parens.

Let me know if you could make the mentioned changes before I merge, or if you'd rather I did it myself.

**Comment by thiagowfx** [comment]
Sure, I will update my patch when I have some time (hopefully this week; if not, then this month). I chose the conventions quite arbitrarily (probably from dohsimpson's style IIRC), so I have no problem with sticking to yours if you prefer so.

**Comment by fcpg** [comment]
Another option would be for you to give me push access rights to the PR branch, as per [this doc](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork), so that I could make the modifications we have been talking about. Once I'm done, you can review them on your side and I'll merge.

**Comment by thiagowfx** [comment]
It looks like this is already the default here:

```
If checked, users with write access to fcpg/vim-osc52 can add new commits to your toupstream branch. You can always change this setting later.
```

You should have write access.

**Comment by thiagowfx** [comment]
Updated the coding conventions to match yours.

Unfortunately I don't know the answers to most of your other questions. I had originally forked https://github.com/dohsimpson/vim-osc52, and my changes were pretty minimal on top of it (you can take a look here: https://github.com/thiagowfx/vim-osc52/commits/master). If @dohsimpson is active then they would be the best to tell you the rationale behind those changes.

As I was saying in a previous comment, my main modification was:

> The major advantage of this is that C-c "just works", and plus there's no need to put a giant line in your vimrc (xmap <F7> y:call SendViaOSC52(getreg('"'))<cr>); rather, a simple vmap <C-c> y:Oscyank<cr>. Thanks.

...to use Control-C as default shortcut (which is more intuitive) and to alias the command to `Oscyank` (instead of the giant `SendViaOSC52(...)`. These are the main changes I care about in this PR.

If you prefer, I could create a separate (way simpler and smaller) PR with just those two changes. Most of the script changes you see here came from the intermediate repository that @dohsimpson created (where I did a simple merge). But if they are confusing for the purposes of clarity (they seem to be, given your questions), then it might be easier to break this down.

Let me know your thoughts.

**Comment by fcpg** [comment]
I checked out your branch and I made some commits.

When I try to push, I got an error:
```
remote: Permission to thiagowfx/vim-osc52.git denied to fcpg.
fatal: unable to access 'https://github.com/thiagowfx/vim-osc52.git/': The requested URL returned error: 403
```

Maybe there is another setting to give me access rights?

Edit: this could be due to upstream being `dohsimpson/vim-osc52 ` and not directly my repo.

**Comment by thiagowfx** [comment]
Ah, I think you are trying to push directly to my repository. I've invited you for direct access to it, you should have gotten an email about it. That will probably work.

**Comment by fcpg** [comment]
Thanks, just pushed my commits. Let me know if this works for you, and if it does I'll merge right away.

**Comment by thiagowfx** [comment]
Just tested it, works for me. :)

**Comment by fcpg** [comment]
Done--thanks again for the submission!

**Pull request merged**
